# Generated by Django 3.2.5 on 2021-07-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image1', models.ImageField(upload_to='productImages')),
                ('product_image2', models.ImageField(upload_to='productImages')),
                ('product_image3', models.ImageField(upload_to='productImages')),
            ],
        ),
    ]
